#!/bin/bash

sum=0.0
directory="$@"
file_list=$(find "$directory" -type f -name "*.mp4")


for file in $file_list; do
    echo "$file"
    duration=$(ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 "$file")
    sum=$(echo "$sum + $duration" | bc)
done

total_minutes=$(echo "scale=0; $sum / 60" | bc)
hours=$(echo "$total_minutes / 60" | bc)
minutes=$(echo "$total_minutes % 60" | bc)

printf "Total duration: %02d:%02d\n" "$hours" "$minutes"
